"use client";

import Link from "next/link";
import { useState } from "react";
import { AppShell } from "@/components/AppShell";
import { FoodItem, searchFoods } from "@/lib/api";

export function DataBackedHome() {
  return <AppShell active="Home"><main className="content"><section className="home-hero branded-home-hero"><div><p className="eyebrow"><span className="eyebrow-dot" /> Your everyday food companion</p><h2>Good food starts with <em>what matters to you.</em></h2><p>Discover recipes, plan meals, understand nutrition, inspect packaged foods, and ask Jiv to help you choose what comes next.</p><div className="home-search"><Link href="/app/recipes" className="search-prompt">Explore the recipe library <span>⌕</span></Link><Link href="/app/jiv" className="scan-button">Ask Jiv <span>✦</span></Link></div></div><div className="home-botanical" aria-label="Botanical illustration"><span>✺</span><i /></div></section><div className="home-capability-intro"><p className="eyebrow">Made for your kitchen</p><h3>Careful data underneath. A warmer way to use it.</h3></div><section className="home-actions"><Link className="home-action home-action-warm" href="/app/recipes"><span className="action-symbol">◒</span><strong>Recipes</strong><small>Browse real dishes by ingredient, cuisine, and profile.</small><b>→</b></Link><Link className="home-action" href="/app/meal-plan"><span className="action-symbol">📅</span><strong>Meal Planning</strong><small>Build a deterministic plan from recipe records.</small><b>→</b></Link><Link className="home-action" href="/app/nutrition"><span className="action-symbol">◌</span><strong>Nutrition</strong><small>Look up IFCT food-composition values.</small><b>→</b></Link><Link className="home-action" href="/app/products"><span className="action-symbol">▧</span><strong>Product Details</strong><small>Inspect and compare stored packaged-food records.</small><b>→</b></Link><Link className="home-action home-action-green" href="/app/jiv"><span className="action-symbol">✦</span><strong>Jiv &amp; Ingredient Recognition</strong><small>Ask, upload, or capture an ingredient for verified help.</small><b>→</b></Link></section></main></AppShell>;
}

export function DataBackedNutrition() {
  const [query, setQuery] = useState("");
  const [foods, setFoods] = useState<FoodItem[]>([]);
  const [error, setError] = useState("");
  async function run() { setError(""); try { setFoods(await searchFoods(query)); } catch (err) { setFoods([]); setError(err instanceof Error ? err.message : "Nutrition database unavailable"); } }
  return <AppShell active="Nutrition"><main className="content"><div className="page-title nutrition-page-title"><p className="eyebrow">IFCT 2017 food composition</p><h2>Know what’s <em>on your plate.</em></h2><p>Search real food-composition records and view values per 100g. Jivanya does not estimate values when a record is unavailable.</p></div><div className="card nutrition-search-card"><div className="nutrition-search"><input className="input search-input" value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => { if (event.key === "Enter") void run(); }} placeholder="Try ragi, atta, dahi…"/><button className="button button-primary" onClick={() => void run()}>Search records</button></div>{error && <p className="form-message">{error}</p>}{foods.length > 0 && <div className="table-scroll"><table className="food-table"><thead><tr><th>Food</th><th>Group</th><th>Energy</th><th>Protein</th><th>Carbohydrate</th><th>Fat</th><th>Fiber</th></tr></thead><tbody>{foods.map(food => <tr key={food.food_id}><td><strong>{food.food_name}</strong><br/><small>{food.food_id}</small></td><td>{food.food_group || "—"}</td><td>{food.energy_kcal} kcal</td><td>{food.protein_g}g</td><td>{food.carbohydrate_g}g</td><td>{food.fat_g}g</td><td>{food.fiber_g}g</td></tr>)}</tbody></table></div>}{!foods.length && !error && <p className="nutrition-empty">Search the IFCT records to begin.</p>}</div></main></AppShell>;
}
