-- Jivanya runtime database schema
-- Nutrition, Recipe, and Market engines

create table if not exists food_items (
    id bigint generated by default as identity primary key,
    food_id text not null unique,
    food_name text not null,
    food_group text,
    energy_kcal double precision default 0,
    protein_g double precision default 0,
    carbohydrate_g double precision default 0,
    fat_g double precision default 0,
    fiber_g double precision default 0,
    calcium_mg double precision default 0,
    iron_mg double precision default 0,
    sodium_mg double precision default 0,
    potassium_mg double precision default 0,
    vitamin_c_mg double precision default 0,
    folate_ug double precision default 0
);

create index if not exists idx_food_items_food_name
    on food_items(food_name);

create index if not exists idx_food_items_food_group
    on food_items(food_group);


create table if not exists ingredient_aliases (
    id bigint generated by default as identity primary key,
    canonical text not null,
    alias text not null,
    unique (canonical, alias)
);

create index if not exists idx_ingredient_aliases_canonical
    on ingredient_aliases(canonical);

create index if not exists idx_ingredient_aliases_alias
    on ingredient_aliases(alias);


create table if not exists recipes (
    recipe_id text primary key,
    recipe_name text not null,
    ingredients_raw text,
    instructions text,
    cuisine text,
    course text,
    diet text,
    prep_minutes integer,
    cook_minutes integer,
    total_minutes integer,
    servings integer,
    source_url text,
    missing_ingredients boolean default false,
    long_prep_time boolean default false,
    large_serving boolean default false
);

create index if not exists idx_recipes_recipe_name
    on recipes(recipe_name);

create index if not exists idx_recipes_cuisine
    on recipes(cuisine);

create index if not exists idx_recipes_diet
    on recipes(diet);


create table if not exists recipe_ingredients (
    id bigint generated by default as identity primary key,
    recipe_id text not null references recipes(recipe_id) on delete cascade,
    ingredient_raw text not null,
    ingredient text not null
);

create index if not exists idx_recipe_ingredients_recipe_id
    on recipe_ingredients(recipe_id);

create index if not exists idx_recipe_ingredients_ingredient
    on recipe_ingredients(ingredient);


create table if not exists products (
    barcode bigint primary key,
    product_name text not null,
    brand text,
    category text,
    countries text,
    energy_100g double precision,
    protein_100g double precision,
    carbohydrates_100g double precision,
    sugars_100g double precision,
    fat_100g double precision,
    saturated_fat_100g double precision,
    fiber_100g double precision,
    sodium_100g double precision,
    ingredients_text text,
    allergens text,
    labels text,
    image_url text,
    last_updated text,
    data_completeness double precision
);

create index if not exists idx_products_product_name
    on products(product_name);

create index if not exists idx_products_category
    on products(category);

create index if not exists idx_products_brand
    on products(brand);
