import os
from typing import Any, Optional

import requests

from app.jiv.providers.base import BaseLLMProvider, LLMResponse, ToolCall
from app.jiv.schemas.chat import ChatMessage


class GeminiProvider(BaseLLMProvider):
    """
    Google Gemini provider implementation via standard REST API.
    Used when LLM_PROVIDER=gemini or GEMINI_API_KEY is configured.
    """

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None) -> None:
        self.api_key = api_key or os.getenv("LLM_API_KEY") or os.getenv("GEMINI_API_KEY")
        self.model = model or os.getenv("LLM_MODEL", "gemini-flash-latest")
        clean_model = self.model if self.model.startswith("models/") else f"models/{self.model}"
        self.endpoint = f"https://generativelanguage.googleapis.com/v1beta/{clean_model}:generateContent"

    def chat(
        self,
        messages: list[ChatMessage],
        tools: list[dict[str, Any]],
        system_instruction: str,
        temperature: float = 0.2,
    ) -> LLMResponse:
        if not self.api_key:
            raise RuntimeError("Gemini API key is not configured. Set GEMINI_API_KEY or LLM_API_KEY.")

        # Convert tools to Gemini function declarations
        gemini_tools = []
        if tools:
            declarations = []
            for t in tools:
                declarations.append({
                    "name": t["name"],
                    "description": t["description"],
                    "parameters": t.get("parameters", {}),
                })
            gemini_tools = [{"function_declarations": declarations}]

        # Convert chat messages
        contents = []
        for msg in messages:
            role = "user" if msg.role in {"user", "system"} else "model"
            parts: list[dict[str, Any]] = []

            if msg.role == "tool":
                parts.append({
                    "functionResponse": {
                        "name": msg.name or "tool_result",
                        "response": {"content": msg.content or ""},
                    }
                })
                contents.append({"role": "function", "parts": parts})
            elif msg.tool_calls:
                for tc in msg.tool_calls:
                    parts.append({
                        "functionCall": {
                            "name": tc["name"],
                            "args": tc.get("arguments", {}),
                        }
                    })
                contents.append({"role": "model", "parts": parts})
            else:
                parts.append({"text": msg.content or ""})
                contents.append({"role": role, "parts": parts})

        payload = {
            "contents": contents,
            "system_instruction": {"parts": [{"text": system_instruction}]},
            "generationConfig": {"temperature": temperature},
        }
        if gemini_tools:
            payload["tools"] = gemini_tools

        timeout_val = int(os.getenv("GEMINI_TIMEOUT", "30"))
        resp = None
        for attempt in range(2):
            try:
                resp = requests.post(
                    f"{self.endpoint}?key={self.api_key}",
                    json=payload,
                    headers={"Content-Type": "application/json"},
                    timeout=timeout_val,
                )
                if resp.status_code == 503 and attempt == 0:
                    import time
                    time.sleep(1.5)
                    continue
                resp.raise_for_status()
                break
            except Exception as exc:
                if attempt == 0 and ("503" in str(exc) or "timeout" in str(exc).lower()):
                    import time
                    time.sleep(1.5)
                    continue
                from app.jiv.providers.mock_provider import MockLLMProvider
                return MockLLMProvider().chat(messages, tools, system_instruction, temperature)

        if resp is None:
            from app.jiv.providers.mock_provider import MockLLMProvider
            return MockLLMProvider().chat(messages, tools, system_instruction, temperature)

        data = resp.json()

        candidates = data.get("candidates", [])
        if not candidates:
            return LLMResponse(text="No response generated by Gemini model.", raw_response=data)

        first_candidate = candidates[0]
        content_parts = first_candidate.get("content", {}).get("parts", [])

        tool_calls: list[ToolCall] = []
        text_parts: list[str] = []

        for part in content_parts:
            if "functionCall" in part:
                fc = part["functionCall"]
                tool_calls.append(ToolCall(name=fc.get("name", ""), arguments=fc.get("args", {})))
            elif "text" in part:
                text_parts.append(part["text"])

        return LLMResponse(
            text="\n".join(text_parts) if text_parts else None,
            tool_calls=tool_calls,
            raw_response=data,
        )
